# Generated by Django 3.0 on 2020-01-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SC', 'Skin Care'), ('HC', 'Hair Care'), ('PC', 'Personal Care'), ('F', 'Fragrances')], default='S', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
        ),
    ]
