# Generated by Django 3.0 on 2020-01-21 09:36

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalon', '0002_auto_20200120_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
