# Generated by Django 3.0 on 2020-01-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysalon', '0004_comments_salonposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post_id',
            new_name='post',
        ),
    ]
