# Generated by Django 3.0 on 2020-01-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysalon', '0006_auto_20200121_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SC', 'Skin Care'), ('HC', 'Hair Care'), ('PC', 'Personal Care'), ('F', 'Fragrances'), ('MK', 'Makeup'), ('MP', 'Manicure $ Pedicure'), ('S', 'suntan')], default='S', max_length=2),
        ),
    ]
